services:
  - type: web
    name: llc-formation-directory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONPATH
        value: /opt/render/project/src

